name: Test
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 24.04
            runs-on: ubuntu-24.04
          - name: Ubuntu 22.04
            runs-on: ubuntu-22.04
          - name: Ubuntu 20.04
            runs-on: ubuntu-20.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
      - run: flutter doctor -v
      - run: flutter --version
      - run: flutter create my_app
      - name: flutter run
        run: |
          cd my_app
          flutter run -d linux --verbose
